name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-lint:
    name: Build, Test & Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Clean Go Cache
        run: go clean -modcache

      - name: Cache Go Modules
        uses: actions/cache@v2
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.mod') }}-${{ github.run_id }} # Cache key
          restore-keys: |
            ${{ runner.os }}-go-mod-${{ hashFiles('**/go.mod') }}-
            ${{ runner.os }}-go-mod-

      - name: Install Dependencies
        run: go mod download

      - name: Build the Application
        run: go build -o api

      - name: Run Unit Tests
        run: go test -v ./...

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run golangci-lint
        run: golangci-lint run --skip-dirs=vendor --skip-dirs=~/go/pkg/mod
